### ISSUE TITLE
Script doesn't see 7z

### ISSUE THREAD

**Issue by bmn001** [cmclark00/batocera_xbla#1]
After selecting my output folder, this script crashes.  It claims it can't find an extraction program and then lists the extraction tools that it supports: `candidates are rar,unrar,7z,7zz,7zzs,unar`

The bug is that I _do_ have 7z installed.  In fact, of those six options, 7z is the _only_ one I have installed (v23.01).

I was able to work around this this by just installing rar.

```
Traceback (most recent call last):
  File "/home/joe/Downloads/xbox360/xbla/work/extract.py", line 32, in <module>
    patoolib.extract_archive(os.path.join(xbla_dir, archive),
  File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 794, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 562, in _extract_archive
    program = find_archive_program(format, 'extract', program=program, password=password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 433, in find_archive_program
    raise util.PatoolError(f"could not find an executable program to {command} format {format}; candidates are " + ",".join(programs))
patoolib.util.PatoolError: could not find an executable program to extract format rar; candidates are rar,unrar,7z,7zz,7zzs,unar

```

**Comment by cmclark00** [comment]
Can you tell me what OS you are using? I haven't touched this code in years, but I'll take a look and see if I can figure it out.

**Comment by bmn001** [comment]
I'm on Ubuntu 24.04.

Clearly not a huuuge issue.  It might just be a bug in patool.

Thanks for this tool btw.  It's been a huge help!

**Comment by cmclark00** [comment]
Cool, I'll give it a run through on my 24.04 vm later tonight when I'm off from work. And thank you, I always knew someone would come along and appreciate this tool lol.

**Comment by cmclark00** [comment]
> After selecting my output folder, this script crashes. It claims it can't find an extraction program and then lists the extraction tools that it supports: `candidates are rar,unrar,7z,7zz,7zzs,unar`
> 
> The bug is that I _do_ have 7z installed. In fact, of those six options, 7z is the _only_ one I have installed (v23.01).
> 
> I was able to work around this this by just installing rar.
> 
> ```
> Traceback (most recent call last):
>   File "/home/joe/Downloads/xbox360/xbla/work/extract.py", line 32, in <module>
>     patoolib.extract_archive(os.path.join(xbla_dir, archive),
>   File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 794, in extract_archive
>     return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program, password=password)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 562, in _extract_archive
>     program = find_archive_program(format, 'extract', program=program, password=password)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/joe/.local/lib/python3.12/site-packages/patoolib/__init__.py", line 433, in find_archive_program
>     raise util.PatoolError(f"could not find an executable program to {command} format {format}; candidates are " + ",".join(programs))
> patoolib.util.PatoolError: could not find an executable program to extract format rar; candidates are rar,unrar,7z,7zz,7zzs,unar
> ```

ok, so in my testing the program could detect 7zip installed via apt, but could not detect p7zip. however, everytime i tried to run it with 7zip it failed and said it could not open the rar archive as an archive. Seems like a bug in patool. I recommend just apt installing unrar, its lightweight and i verified it still works that way

I am going to close this since there is no way for me to fix the primary issue.

**Comment by cmclark00** [comment]
Bug with patool, Not something I can fix unfortunately.
